update workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -17,7 +17,7 @@ jobs:
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
-          ruby-version: "4.0.2"
+          ruby-version: "4.0.4"
           bundler-cache: true
 
       - name: Set Release Version
@@ -29,9 +29,14 @@ jobs:
         env:
           GEM_PRIVATE_KEY: ${{ secrets.GEM_PRIVATE_KEY }}
         run: |
-          mkdir -p ~/.gem
-          echo "$GEM_PRIVATE_KEY" > ~/.gem/gem-private_key.pem
-          chmod 0600 ~/.gem/gem-private_key.pem
+          if [ -z "$GEM_PRIVATE_KEY" ]; then
+            echo "::error title=Missing Gem Signing Key::GEM_PRIVATE_KEY secret is not set. Execution cannot continue because the gem must be signed."
+            exit 1
+          else
+            mkdir -p ~/.gem
+            echo "$GEM_PRIVATE_KEY" > ~/.gem/gem-private_key.pem
+            chmod 0600 ~/.gem/gem-private_key.pem
+          fi
 
       - name: Build Gem
         run: gem build leechtop_downloader.gemspec
